### ISSUE TITLE
[bug]: https://hub.helm.sh shows not existing chart from incubator

### ISSUE THREAD

**Issue by rimusz** [helm/hub#17]
https://hub.helm.sh/charts/incubator/artifactory

**Comment by prydonius** [comment]
I believe it comes from here: https://github.com/helm/charts/tree/cd5cfc462126d8d3ae27eea5f97f343d69d158bf/incubator/artifactory, before it was moved to stable in https://github.com/helm/charts/commit/689cc8b6d816e2dfe2f72c59f296a2013bb9247c. We didn't have a good process for deprecating charts back end, so the incubator chart was just deleted instead of deprecated. To properly deprecate it, a PR would need to re-add the chart as it was in https://github.com/helm/charts/tree/cd5cfc462126d8d3ae27eea5f97f343d69d158bf/incubator/artifactory and deprecate it according to the process described in https://github.com/helm/charts/blob/master/PROCESSES.md#deprecating-a-chart.

**Comment by rimusz** [comment]
ok, will do that tomorrow

**Comment by eldada** [comment]
@prydonius - I have created https://github.com/helm/charts/pull/9767. Should I fix the linting errors?

**Comment by rimusz** [comment]
sorted, closing

**Comment by prydonius** [comment]
thanks a lot!
