### ISSUE TITLE
Image in Readme not rendered in page

### ISSUE THREAD

**Issue by Aaquiff** [helm/hub#280]
We have a Readme file at the root of the chart. It refers to a PNG image at the same location which is packaged into the chart. However, this image is not rendered in the Helm hub page for the chart.

[Chart page](https://hub.helm.sh/charts/wso2/am-pattern-1)

**Comment by mattfarina** [comment]
@Aaquiff The Helm Hub using the `icon` property from the `Chart.yaml` file. The [docs for that](https://helm.sh/docs/topics/charts/#the-chartyaml-file) note:

> icon: A URL to an SVG or PNG image to be used as an icon (optional).

The Helm Hub does not pickup an image in the root of a chart archive for display.

Hope that helps explain what you're seeing.

**Comment by mattfarina** [comment]
While I have not tried it... a data uri should work for the `icon` property as well. See https://css-tricks.com/lodge/svg/09-svg-data-uris/ for an example. This is the style of how the image is rendered... https://github.com/helm/monocular/blob/060b11327c00956a706c218cc2c3ad4849f42f17/frontend/src/app/chart-details/chart-details.component.html#L12

**Comment by Aaquiff** [comment]
@mattfarina, this is not about the icon. This is an image in the Readme that is not rendered.

**Comment by mattfarina** [comment]
Sorry about the confusion.

@prydonius I think I know what's going on here. Do you have any direction or ideas on this?

**Comment by mattfarina** [comment]
We had some more discussion on this over on the Artifact Hub. If I remember correctly, this isn't an easy problem. Every asset needs to be kept locally to serve up. The whole chart packages aren't kept by Monocular or the Artifact Hub. Instead, the needed data is extracted. This would means extracting and storing other assets from the package.

In doing so, you open the door to store a lot of assets and open to possible security issues. For example, it's possible to DOS a system that does this without certain checks on what it's storing and serving.

So, adding a feature like this would take time and a lot of consideration.

Since the Helm Hub has now been turned down and its work has been handed over to the Artifact Hub, I'm closing this issue. It is one to be discussed there but not a high priority there.
