### ISSUE TITLE
Document guidelines for inclusion of Chart repository in distributed search

### ISSUE THREAD

**Issue by mattfarina** [helm/hub#3]

**Comment by mattfarina** [comment]
One such guideline will need to be:

We cannot include repositories physically hosted in US embargoed countries.

The CNCF/Linux Foundation is a US non-profit and needs to comply with US laws.

**Comment by rimusz** [comment]
yes, good point

**Comment by dankohn** [comment]
These aren't all "legal" considerations but many are legal-adjacent. 

1) For trademarked projects, will we allow anybody at all to submit a chart? E.g., for MySQL, can anybody submit a chart that could become the "official" MySQL chart, or only someone from Oracle? If someone from Oracle objected, would the community have processes in place to modify or remove a chart? This gets into trademark considerations as well as security / squatting issues, I expect.

2) How is license info communicated, for the chart vs. the software? I'm assuming that the charts themselves would be licensed under Apache-2.0. It should be made clear to users that this doesn't mean the underlying software itself is also all Apache-2.0. I would hope that an "approved" chart would need to accurately describe the license(s) for the applicable software, ideally using SPDX identifiers (https://spdx.org/licenses) to make automation more feasible.

3) What's the escalation process for reporting charts that are malware or include vulnerable versions of the software. Will these charts be pulled until they can be updated?

4) Since we aren't actually distributing the software, the export controls aren't critical. (It does make sense to add a policy not to list charts that point to repos under a TLD for a sanctioned country.)

Cc @swinslow

**Comment by mattfarina** [comment]
@dankohn sorry I didn't link it here... we started a doc at https://github.com/helm/hub/pull/5

**Comment by dankohn** [comment]
>Do we limit the licenses? Do we say only OSI approved licenses?

I see no need to limit the license or require OSI-approved. But I would love to at least support (and ideally require) SPDX labeling, as it would enable a ton of useful automation later.

**Comment by mattfarina** [comment]
This was documented via https://github.com/helm/hub/pull/5. Closing this issue.
