### ISSUE TITLE
charts not rendering properly

### ISSUE THREAD

**Issue by mlbiam** [helm/hub#305]
Going to one of our newly built charts in helm hub (https://hub.helm.sh/charts/tremolosecurity/openunison-k8s-activedirectory):

1.  The graphic in our `icon` isn't rendering (https://drive.google.com/open?id=1k3mhr9cVcFbDTRSSMRo_eKFfKISRVPwt)
2. When the chart loads there's a spinning circle that looks like something is supposed to happen but doen't.

Is there something I need to fix in my chart?

Thanks

**Comment by mattfarina** [comment]
There are two things going on.

1. The contents listed from on the chart listing pages come from a `README.md` file that sits alongside the `Chart.yaml` file. You can read about them at https://helm.sh/docs/topics/charts/#chart-license-readme-and-notes
2. The `icon` in the `Chart.yaml` needs to be a URL to an SVG or PNG file. See https://helm.sh/docs/topics/charts/#the-chartyaml-file. Your chart is linking to a page that displays the image in Google Drive rather than to the image itself. To display you need a URL directly to the image itself.

**Comment by mlbiam** [comment]
thanks for the great explanation.  Once i make updates, how long does it take to show up?

**Comment by mlbiam** [comment]
Thanks again for the details!
