### ISSUE TITLE
Add mandatory category in helm charts

### ISSUE THREAD

**Issue by camilamacedo86** [helm/hub#343]
would be nice to know what is the category of the chart for we are able to search in the repo. For example, I'd like to check all lib charts and/or I'd like to search for all database kinds and etc..

**Comment by mattfarina** [comment]
@camilamacedo86 unfortunately, we can't add mandatory categories for a couple reasons:

- It would be a breaking change that's not backwards compatible. The breaking change is a big deal and the non-backwards compatible change raises the barrier.
- Charts can be used in places where a category isn't really needed. For example, in internal company workflows.

There are two things that do come to mind:

1. https://artifacthub.io/ has better search capabilities and faceted search. This may be more useful for discovery.
2. It would be great to have an audit tool someone can run to give them recommendations for public listing. This would be additive.

**Comment by absoludity** [comment]
> I'd like to check all lib charts

This part could already be done using the [`type` field in the Chart.yaml](https://helm.sh/docs/topics/charts/#chart-types) I think? But it's not very useful with only two options.

More generally, yes, it makes sense that a more generic `category` field can't be mandatory, but would an optional `category` field in the chart.yaml which can accept multiple values from a set of defined categories, be worth considering, or do you think there is no place for a chart category? I know search can be better at finding what people really need, but it seems people still want to filter by category.

As it would be optional, we could prompt people when linting a chart, and verify allowed categories when linting (but not enforce, etc.). This could be useful both for helm hub and things like Kubeapps (which is why I'm asking :) ). (Seems this discussion should be against helm/helm though? Let me know if I should start a feature request there, or whether it's already been considered - I can't see an existing issue.)

**Comment by mattfarina** [comment]
As the Helm Hub has been turned down, I'm closing this issue.
