### ISSUE TITLE
Agree on whether or how to handle "official" charts in hub

### ISSUE THREAD

**Issue by scottrigby** [helm/hub#41]

**Comment by prydonius** [comment]
Could you elaborate on what this means?

**Comment by scottrigby** [comment]
@prydonius Wow somehow missed your reply. I believe this was from a charts chat meeting, and related to charts hosted by orgs who also maintain the application installed by the chart.

**Comment by marckhouzam** [comment]
I think the question raised in this issue is important.

Once the stable repo is no longer available, how will a user choose between multiple charts for the same product.  For example, if a user wants to install Grafana, as of today, HelmHub provides:

- bitnami/grafana
- incubator/grafana (I assume this will go away)
- flagger/grafana
- cloudposse/grafana
- stable/grafana (I assume this will go away)

What criteria should a user base themselves on to choose between these?

I think this likens to choosing an image on Dockerhub.  But Dockerhub has official images https://docs.docker.com/docker-hub/official_images/. Then again, there is no official image for Grafana on DockerHub, but there is a grafana/grafana.  As a user I assume that the grafana user is legit and therefore that I can trust their image (maybe I'm wrong?)

I guess this comes down to: will there be some kind of vetting process for big name charts?

**Comment by davidkarlsen** [comment]
The grafana/grafana image is real - so it is "official", i.e. produced by grafana-project. Choosing the most attractive chart could depend on how it is designed - but it would be very interesting to have statistics for downloads of charts in order to be able to quantify their popularity.

**Comment by codiophile** [comment]
I just posted this [comment](https://github.com/helm/charts/issues/21100#issuecomment-649468864) and figured it's probably more of a decision for the Helm Hub owners than the `stable` repository owners.

I think @marckhouzam makes a very valid point, but as of today `stable` looks official, so as a user I would choose `stable/grafana`. The real problem will emerge once the `stable` repository is de-listed. Unless you're familiar with one of the vendors, it will be quite hard to decide which chart to use.

I think official charts would be immensely valuable for the Helm community. It would give the charts and Helm itself more credibility. If you're also able to decide on some strict standards for official charts that make it easy to reuse configuration between different charts, that would improve the user experience even further. (Most `stable` charts are already following some standards. It's generally possible to copy ingress configuration between charts and persistence always looks very similar. However, there are more things that could be standardised.)

> On Docker Hub it is very easy to identify official images. I think a similar system needs to be established on Helm Hub, before de-listing the `stable` repository. There should also be a clear migration path for chart owners in this repository, to convert their charts to official Helm charts. On Docker Hub, official images are in the root of the repository. I don't know how easy that would be to implement for Helm Hub, but it seems advantageous to use the same pattern as Docker Hub.

As mentioned in the comment, I made on the issue in the charts repository, I think it's critical that we have such a system in place on the Helm Hub before the `stable` repository is de-listed. I don't know what governance you have in place for managing this kind of decision, but I'm willing to get involved to make this happen.

**Comment by desaintmartin** [comment]
> I think @marckhouzam makes a very valid point, but as of today `stable` looks official, so as a user I would choose `stable/grafana`. The real problem will emerge once the `stable` repository is de-listed. Unless you're familiar with one of the vendors, it will be quite hard to decide which chart to use.

There is actually ongoing efforts to make some chart hosted in their upstream project repository as much as possible (for my parts, kubernetes-dashboard, elasticsearch for now, probably oauth2-proxy or others in the near future, and I've seen discussions about grafana / prometheus-* as well).
This solves the problem of trust and make them really official, even in the case that they are maintained by community like kubernetes-dashboard, or prometheus-operator in its future home.


About the "officialness" of a chart, I suppose an "official" label for charts would be a good idea.

**Comment by codiophile** [comment]
@desaintmartin I think that is great and it does help making charts look more credible. Although I still think that a curated list of official charts managed centrally by the Helm Hub would be great. They would still be maintained by their respective projects, but vouched for by the Helm Hub.

Compliance with standards could be verified by automated testing. So the only work, for the central team, would be to maintain those automated tests and add/remove charts from the official list, based on compliance and other criteria.

I do agree that https://github.com/helm/charts should be deprecated and de-listed, since it's not a great way of managing a list of official charts, but we need to make sure that there is something there to replace it. New chart repositories may be created organically, but without anything to denote them as official, it may be hard for the community to know which one to use and which one to focus development efforts on.

One of the things I dislike the most about Ansible is how hard it is (impossible?) to find official looking roles on Ansible Galaxy. Everything looks like it's just written by some random guy on the Internet and nothing looks quite official (I suppose there might be exceptions). Often times you end up writing your own custom roles, because you didn't find anything that looked trustworthy enough. (Disclaimer: I have very limited experience with Ansible and Ansible Galaxy. Perhaps it's not as bad as my impression.) Regardless of whether that is just my shallow first impression of Ansible Galaxy, I don't want anyone to have such a first impression of the Helm Hub.

**Comment by mattfarina** [comment]
We are looking at migrating from the Helm Hub to the Artifact Hub. This issue has already been file there at https://github.com/artifacthub/hub/issues/542

**Comment by mattfarina** [comment]
Closing as the Helm Hub now redirects to the Artifact Hub. The Artifact Hub has an issue for this.
