### ISSUE TITLE
Display chart health, usage, etc

### ISSUE THREAD

**Issue by scottrigby** [helm/hub#42]

**Comment by prydonius** [comment]
Should this issue exist in Monocular?

**Comment by scottrigby** [comment]
License too. See [Charts Chat notes September 17, 2019](https://docs.google.com/document/d/1h6UTTuNRbFI81higrN3JUV2XxyzqqVjZET4Xz4WTR-8/edit#)

**Comment by phumberdroz** [comment]
I would like to help with this.

In particular I am concerned with a decentralised repo approach and possible unknown source code of charts.

These things I would like to see implemented in a new helm hub:
- File Browser with similar functionality to github when you click a line number
- Notary functionality where we can put out a PSA if a popular chart changes it chart contents for an older release. 
 - a policy that unlisting a chart version that is older than for example 3 days should be deprecated instead of just removed b/c some people could rely on it already similar to NPM [policy](https://www.npmjs.com/policies/unpublish)
- Diff between versions to see what actually changed
- Release notifications via mail, slack, rss feed?

These are just ideas that I have in my mind some of the things I have already implemented b/c I found the mono repo hard to browse for changes.

**Comment by phumberdroz** [comment]
Also something to consider is what happens if a location of repository moves?
https://github.com/helm/hub/pull/213 (example) 
How do user get notified about these kind of changes? 
I currently find this information hard access and not really transparent.

**Comment by mattfarina** [comment]
Closing as the Helm Hub has been deprecated and replaced by the Artifact Hub
