### ISSUE TITLE
hub search is broken

### ISSUE THREAD

**Issue by rafik8** [helm/hub#55]
When navigating to hub website, I would like to search if a chart exists for solution I  would like to deploy to my Kubernetes cluster. When searching for the chart using the form (https://hub.helm.sh/charts?q=istio), I got 'There are no charts' message displayed. 

![image](https://user-images.githubusercontent.com/13514337/54144920-b2c0c500-4424-11e9-9c3c-a664fa9fa016.png)

By going back to all charts view(https://hub.helm.sh/charts/) and use the browser inline search, I was been able to locate the chart:

![image](https://user-images.githubusercontent.com/13514337/54145057-07fcd680-4425-11e9-9103-e737c7ad120b.png)

**Comment by prydonius** [comment]
the error from the JS console is:
> vendor.e641b3050a34dc23e639.bundle.js:1 ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'match' of undefined
> TypeError: Cannot read property 'match' of undefined

Looks like the issue is that some of the new chart repositories added to the Hub may not have maintainer names defined. When this is the case, https://github.com/helm/monocular/blob/060b11327c00956a706c218cc2c3ad4849f42f17/frontend/src/app/shared/services/charts.service.ts#L79 will return an array with some values `undefined`, and it would then throw that error in https://github.com/helm/monocular/blob/060b11327c00956a706c218cc2c3ad4849f42f17/frontend/src/app/shared/services/charts.service.ts#L89

We should be able to just return false if `keyword === undefined` here https://github.com/helm/monocular/blob/060b11327c00956a706c218cc2c3ad4849f42f17/frontend/src/app/shared/services/charts.service.ts#L89 to protect against this.

**Comment by prydonius** [comment]
cc @Dean-Coakley, I think you discovered this issue too

**Comment by Dean-Coakley** [comment]
Yeah, I hope to open a PR this week!

**Comment by mattfarina** [comment]
With recently deploys of the hub using a newer version of Monocular the search issues are fixed.
